fos_user:
    db_driver:              orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name:          main
    user_class:             Instinct\Bundle\UserBundle\Entity\User
    use_listener:           true
    use_username_form_type: true
    model_manager_name:     null  # change it to the name of your entity/document manager if you don't want to use the default one.
    from_email:
        address:        webmaster@example.com
        sender_name:    Admin
    profile:
        form:
            type:               fos_user_profile
            handler:            fos_user.profile.form.handler.default
            name:               fos_user_profile_form
            validation_groups:  [Profile]
    change_password:
        form:
            type:               fos_user_change_password
            handler:            fos_user.change_password.form.handler.default
            name:               fos_user_change_password_form
            validation_groups:  [ChangePassword]
    registration:
        confirmation:
            from_email: # Use this node only if you don't want the global email address for the confirmation email
                address:        ...
                sender_name:    ...
            enabled:    false # change to true for required email confirmation
            template:   FOSUserBundle:Registration:email.txt.twig
        form:
            type:               fos_user_registration
            handler:            fos_user.registration.form.handler.default
            name:               fos_user_registration_form
            validation_groups:  [Registration]
    resetting:
        token_ttl: 86400
        email:
            from_email: # Use this node only if you don't want the global email address for the resetting email
                address:        ...
                sender_name:    ...
            template:   FOSUserBundle:Resetting:email.txt.twig
        form:
            type:               fos_user_resetting
            handler:            fos_user.resetting.form.handler.default
            name:               fos_user_resetting_form
            validation_groups:  [ResetPassword]
    service:
        mailer:                 fos_user.mailer.default
        email_canonicalizer:    fos_user.util.canonicalizer.default
        username_canonicalizer: fos_user.util.canonicalizer.default
        token_generator:        fos_user.util.token_generator.default
        user_manager:           fos_user.user_manager.default
    template:
        engine: twig
    group:
        group_class:    Instinct\Bundle\UserBundle\Entity\Group # Required when using groups
        group_manager:  fos_user.group_manager.default
        form:
            type:               fos_user_group
            handler:            fos_user.group.form.handler.default
            name:               fos_user_group_form
            validation_groups:  [Registration]


security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall pour les pages de connexion, inscription, et recuperation de mot de passe
        login:
            pattern:   ^/user/(login$|register|resetting)  # Les adresses de ces pages sont login, register et resetting
            anonymous: true

        main:
            pattern:    ^/
            form_login:                
                # the user is redirected here when he/she needs to login
                login_path:                     /user/login

                # if true, forward the user to the login form instead of redirecting
                use_forward:                    false

                # submit the login form here
                check_path:                     /user/login_check

                # by default, the login form *must* be a POST, not a GET
                post_only:                      true

                # login success redirecting options (read further below)
                always_use_default_target_path: false
                default_target_path:            /user/profile
                target_path_parameter:          _target_path
                use_referer:                    true

                # login failure redirecting options (read further below)
                failure_path:                   /user/login
                failure_forward:                false
                
                remember_me:    true
                
                provider:       fos_userbundle
                csrf_provider:  form.csrf_provider
            remember_me:
                key:        %secret%
            logout:
                path:       /user/logout
                target:     /user
            anonymous:  true

    access_control:
        - { path: ^/user/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/admin, role: ROLE_SUPER_ADMIN }
        - { path: "^/([a-zA-Z_-]*/)?admin/", role: ROLE_ADMIN }
        
imports:
    - { resource: "@InstinctUserBundle/Resources/config/security/role_hierarchy.yml" }
    - { resource: "@InstinctUserBundle/Resources/config/security/acl.yml" }
        
