home:
    pattern: /{page}
    defaults: { _controller: "InstinctNewsBundle:News:index", page: 1 }
    requirements:
        page: \d+

instinct_user:
    prefix:   /
    resource: "@InstinctUserBundle/Resources/config/routing.yml"

instinct_menu:
    prefix:   /menu
    resource: "@InstinctMenuBundle/Resources/config/routing.yml"

instinct_news:
    prefix:   /news
    resource: "@InstinctNewsBundle/Resources/config/routing.yml"
